[signal sampleRate] = ParseAudioData('/home/amy/src/MATLAB/VocalizationTracking/2008Experiments/CBAusfmMale.call1');

signalLength = length(signal);
signal = signal - mean(signal);
cropSignal = signal;

duration = signalLength/sampleRate;
%==========================================================================
%Display initial spectrogram
%==========================================================================
plotFreqSamples = 2^10;
plotTimeSamples = 2^10;
windowDuration = 70/80000;
dbRange = 30;
%frequencyRange = [0 sampleRate/2]; %I changed frequecy range to 160000 for consistancy in comparing spectrograms
[spectrogram,t,f, handles] = NonparametricSpectrogramV2(signal, ...
                                             sampleRate, ...
                                             'nTimes',plotTimeSamples, ...
                                             'nFrequencies',plotFreqSamples, ...
                                             'windowDuration',windowDuration, ...
                                             'plotType',1,...
                                             'spectrogramType',2, ...
                                             'dbRange', dbRange,...
                                             'frequencyRange', [0 160000]);